name: Rust build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths-ignore:
    - "**.md"
    - "**.gif"
  pull_request:
    paths-ignore:
    - "**.md"
    - "**.gif"
  # manual trigger
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux]
        include:
        - build: linux
          os: ubuntu-latest
          rust: stable
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Rust toolchain
      run: rustup toolchain install ${{ matrix.rust }} --profile minimal
    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Run tests
      run: |
        df -h .
        cargo clean
        cargo test --verbose
